Get-AppxPackage Clipchamp.Clipchamp | Remove-AppxPackage 
Get-AppxPackage Microsoft.BingNews | Remove-AppxPackage 
Get-AppxPackage Microsoft.BingWeather | Remove-AppxPackage 
Get-AppxPackage Microsoft.GamingApp | Remove-AppxPackage 
Get-AppxPackage Microsoft.GetHelp | Remove-AppxPackage 
Get-AppxPackage Microsoft.Getstarted | Remove-AppxPackage 
Get-AppxPackage Microsoft.MicrosoftOfficeHub | Remove-AppxPackage 
Get-AppxPackage Microsoft.MicrosoftSolitaireCollection | Remove-AppxPackage 
Get-AppxPackage Microsoft.People | Remove-AppxPackage 
Get-AppxPackage Microsoft.PowerAutomateDesktop | Remove-AppxPackage 
Get-AppxPackage Microsoft.Todos | Remove-AppxPackage 
Get-AppxPackage Microsoft.WindowsAlarms | Remove-AppxPackage 
Get-AppxPackage microsoft.windowscommunicationsapps | Remove-AppxPackage 
Get-AppxPackage Microsoft.WindowsFeedbackHub | Remove-AppxPackage 
Get-AppxPackage Microsoft.WindowsMaps | Remove-AppxPackage 
Get-AppxPackage Microsoft.WindowsSoundRecorder | Remove-AppxPackage 
Get-AppxPackage Microsoft.Xbox.TCUI_1.23.28004 | Remove-AppxPackage 
Get-AppxPackage Microsoft.XboxGamingOverlay | Remove-AppxPackage 
Get-AppxPackage Microsoft.XboxGameOverlay | Remove-AppxPackage 
Get-AppxPackage Microsoft.XboxSpeechToTextOverlay | Remove-AppxPackage 
Get-AppxPackage Microsoft.YourPhone | Remove-AppxPackage 
Get-AppxPackage Microsoft.ZuneMusic | Remove-AppxPackage 
Get-AppxPackage Microsoft.ZuneVideo | Remove-AppxPackage 
Get-AppxPackage MicrosoftCorporationII.MicrosoftFamily | Remove-AppxPackage 
Get-AppxPackage MicrosoftTeams | Remove-AppxPackage 
Get-AppxPackage Microsoft.549981C3F5F10 | Remove-AppxPackage 
AppxPackage MicrosoftTeams* | Remove-AppxPackage

